### ISSUE TITLE
👋 Hi from :dependabot: team!

### ISSUE THREAD

**Issue by jeffwidman** [merchstack/actions-set-secret#7]
👋 Hi from the :dependabot: team!

I saw this linked to by another Dependabot user, and think it's awesome that you hacked this together @dcrdev. While we obviously can't officially endorse stuff written by the community, we're always more than happy to help answer questions... so as the maintainer of the action if you ever run into issues with it, don't hesitate to swing by our issue tracker and ask for help. 

Cheers!
Jeff

**Comment by dcrdev** [comment]
> 👋 Hi from the :dependabot: team!
> 
> I saw this linked to by another Dependabot user, and think it's awesome that you hacked this together @dcrdev. While we obviously can't officially endorse stuff written by the community, we're always more than happy to help answer questions... so as the maintainer of the action if you ever run into issues with it, don't hesitate to swing by our issue tracker and ask for help.
> 
> Cheers! Jeff

Thanks for the reach out @jeffwidman (super cool) and the tool in general - it saves us a boatload of time each month.
